name: Push latest verion to DockerHub

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

jobs:
  dockerhub-latest:
    needs: [test-ubuntu, test-macos, test-wsl]
    runs-on: ubuntu-latest
    env:
        PIP_NO_CACHE_DIR: 0

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: |
          python -m unittest discover -s tests -v
      - name: Build and Push to DockerHub
        run: |
          DOCKER_TAG="unfor19/appy:latest"
          docker build . --file Dockerfile.multistage --tag "${DOCKER_TAG}"
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "${DOCKER_TAG}"
