# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Release to PyPi and DockerHub

on:
  release:
    types: [published, edited]

jobs:
  pypi:
    runs-on: ubuntu-latest
    env:
      RELEASE_REF: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools==44.1.0 wheel==0.34.2 twine==3.1.1
          pip install -r requirements.txt
      - name: Test
        run: |
          python -m unittest discover -s tests -v
      - name: Build Package
        run: |
          RELEASE_VERSION=$(echo "$RELEASE_REF" | sed "s|refs\/tags\/v||g")
          [[ $RELEASE_VERSION = *.*.* ]] && echo -n $RELEASE_VERSION > ./version
          python setup.py sdist bdist_wheel
          twine check ./dist/*
      - name: Publish to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.PIP_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PIP_PASSWORD }}
          TWINE_NON_INTERACTIVE: true
        run: |
          RELEASE_VERSION=$(echo "$RELEASE_REF" | sed "s|refs\/tags\/v||g")
          [[ $RELEASE_VERSION = *.*.* ]] && twine upload ./dist/* || true

  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools==44.1.0 wheel==0.34.2 twine==3.1.1
      - name: Test
        run: |
          python -m unittest discover -s tests -v
      - name: Build and Push to DockerHub
        run: |
          RELEASE_VERSION=$(echo "$RELEASE_REF" | sed "s|refs\/tags\/v||g")
          [[ ! $RELEASE_VERSION =~ *.*.* ]] && exit 0
          export DOCKER_TAG="unfor19/appy:${RELEASE_VERSION}"
          docker build . --file Dockerfile --tag "${DOCKER_TAG}"
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "${DOCKER_TAG}"
